name: swiss_elections_study
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda-lock=2.5

  # Base dependencies
  - pandas=2.2
  - numpy=2.2
  - matplotlib=3.10
  - pyarrow=19.0
  - scipy=1.15
  - pip:
      - pyaxis==0.4.*
platforms:
  - linux-64
